In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

by using mathametics find theta_best and also find y_predit

In [2]:
df = pd.read_csv("Untitled spreadsheet - Sheet1.csv")
x = df[['Volume','Weight']].values
y = df[['CO2']].values


In [3]:
x_b = np.c_[np.ones((36, 1)), x]
theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)
theta_best

array([[7.96947193e+01],
       [7.80525753e-03],
       [7.55094727e-03]])

In [4]:
x_new = np.array([[2000,1746],[1600,1390]])
x_new_b = np.c_[np.ones((2,1)),x_new]
y_predict = x_new_b .dot(theta_best)
y_predict

array([[108.48918828],
       [102.67894804]])

by using linear regression model 

In [5]:
lin_reg = LinearRegression()
lin_reg.fit(x,y)
lin_reg.intercept_

array([79.69471929])

In [6]:
lin_reg.coef_

array([[0.00780526, 0.00755095]])

In [7]:
theta_best = np.array([[79.69471929],[0.00780526],[0.00755095]])
theta_best

array([[7.96947193e+01],
       [7.80526000e-03],
       [7.55095000e-03]])

In [8]:
x_new = np.array([[2000,1746],[1600,1390]])
y_predict = lin_reg.predict(x_new)
y_predict

array([[108.48918828],
       [102.67894804]])